[project]
name = "psychopy-translations"
version = "2026.2.1"
requires-python = ">=3.10, <3.13"
description = "Python module containing the translations necessary for PsychoPy and PsychoPy Studio"
readme ={file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "Open Science Tools Ltd", email = "support@opensciencetools.org"},
]
maintainers = [
    {name = "Open Science Tools Ltd", email = "support@opensciencetools.org"},
]
    
dependencies = [
    "babel",
    "polib",
    "six",
    "pyyaml",
    "autopep8",
    "i18next",
    "pojson"
]