name: Fetch translate strings

on:
  workflow_dispatch:  # manual
  # cron nightly at 2am on first of month (to avoid too many PRs being created)
  schedule:
    - cron: '0 2 1 * *'

permissions:
  contents: write
  # allow github-actions bot to create PRs
  pull-requests: write

jobs:

  fetch_strings:
    name: Fetch translation strings

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Checkout psychopy (lib)
      uses: actions/checkout@v3
      with:
        repository: psychopy/psychopy
        ref: ${{ github.event.inputs.branch }}
        path: source/psychopy
    - name: Checkout psychopy-studio
      uses: actions/checkout@v3
      with:
        repository: psychopy/psychopy-studio
        ref: ${{ github.event.inputs.branch }}
        path: source/psychopy-studio
    - name: Find and checkout plugins
      run: |
        # fetch plugins.json (a list of dicts including "repo" key with the git url)
        curl -s https://www.psychopy.org/plugins.json -o plugins.json
        # extract the git urls and checkout each plugin
        cat plugins.json | jq -r '.[].repo' | while read repo; do
          # if repo is null or blank string then skip
          if [ -z "$repo" ] || [ "$repo" = "null" ]; then
            continue
          fi
          name=$(basename $repo .git)
          echo "Cloning to source/$name from $repo using default branch with depth 1"
          git clone --depth 1 $repo source/$name
        done
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install UV
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true
    - name: Install translation dependencies
      run: |
        # minimal dependencies to run the translation template generation script
        uv pip install babel polib packaging six pyyaml autopep8 i18next
        # then psychopy with no further deps
        uv pip install -e source/psychopy/. --no-deps  # to get __version__
    - name: Generate PsychoPy Alerts text for localization
      working-directory: source/psychopy/psychopy/alerts/alertsCatalogue
      run: |
        python generateAlertmsg.py
    - name: Generate PsychoPy Prefs hints for localization
      working-directory: source/psychopy/psychopy/preferences
      run: |
        python generateHints.py

    - name: Generate .pot (translation template)
      working-directory: source
      run: |
        # NB run the command in source with input-dirs=. so the paths are relative to source/ 
        # used to be --width=79 but trying now with --no-wrap
        # using add-location=file to add the filename *without* the constantly-changing line numbers
        pybabel extract \
          -F ../babel.cfg \
          --input-dirs=. --project=PsychoPy \
          --version=$(uv run python -c "import psychopy; print(psychopy.__version__)") \
          --no-wrap \
          --sort-output \
          --add-location=file \
          --output-file=../messages_new.pot

    - name: Compare old/new .pot files and update .po files
      run: |
        python compare_old_new.py -v
        # then move messages_new.pot to messages.pot (overwriting old one) for next round of updates
        mv messages_new.pot messages.pot

    - name: Git check status on po files
      run: |
        # pot file will have changed date to current date, so just check po files for changes to commit
        git add -A locale/
        git status
    
    - name: Git commit and PR creation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # to authenticate with GitHub API for PR creation
      run: |
        git config --local user.name "PsychoPy devops"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # if changes create a PR with github cli (gh) - but only if there are changes to commit
        if (git status | grep -q 'Changes to be committed:')
        then
          git add messages.pot # now also add pot, if there are changes to po files
          echo 'Creating a PR with gh cli...'
          # create a new branch for the PR
          branch="updated-translations-$(date +%Y%m%d%H%M%S)"
          git checkout -b $branch
          git commit -m "Automated update of translations"
          git push --set-upstream origin $branch
          # create the PR
          gh pr create --title "Automated update of translations" --body "This PR updates the translation template and PO files with new strings from psychopy, psychopy-studio and all official plugins"
        else
          echo 'No changes to commit, skipping PR creation.'
        fi

    - name: Upload new/old .pot and ja_JP/fr_FR .po files as artifact to check
      uses: actions/upload-artifact@v4
      if: always()  # upload even if previous steps fail, to check what went wrong
      with:
        name: translations
        retention-days: 7
        path: |
          messages_new.pot
          messages.pot
          locale/ja_JP/LC_MESSAGES/messages.po
          locale/fr_FR/LC_MESSAGES/messages.po
